name: C CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install tools
      run: sudo apt-get update && sudo apt-get install -y cppcheck clang gcc make

    - name: Static analysis (cppcheck)
      run: cppcheck --enable=all --error-exitcode=1 .

    - name: Build
      run: make

    - name: Run program (optional)
      run: ./executor sample_commands.txt || true
